permalink: /:title
url: "http://jslinterrors.com"

authors:
    jallardice:
        name: James Allardice
        avatar: https://gravatar.com/avatar/321be24529d43c2bacc7167337299e3d.png
        gplus: https://plus.google.com/110229746715330149995?rel=author
        twitter: james_allardice
        github: jamesallardice
        desc: "an enthusiastic young JavaScript developer at <a href='http://globalpersonals.co.uk/' target='_blank'>Global Personals</a> <em>(we're looking for front-end developers so <a href='http://careers.stackoverflow.com/jobs/34245/frontend-developer-global-personals&a=EswC1J6' target='_blank'>please apply</a>)</em>. He is passionate about writing clean, maintainable JavaScript and uses JSHint every day to help achieve this."